//! **A `serial` or identity column on a table with no key takes its number** — debt #93, held to
//! PostgreSQL 19's answers.
//!
//! A table with no primary key carries an internal row id at position 0, so every column it was
//! declared with sits one later in the stored row. `CREATE TABLE` recorded the column a sequence
//! fills by its position in the **statement**, and the sequence filled the row id's slot instead:
//! `id` stayed NULL and the insert was `23502`, while the same table with a key — which has no row
//! id to count — was fine (s1's probe, `esker-coord/s1-unit-j/j-probe2.log`). `ALTER TABLE … ADD
//! COLUMN … serial` and an inherited sequence already counted the row id, by name.
//!
//! `corpus/pg19_serial_without_a_key.txt` is the capture and the replay is the test of record; the
//! tests after it pin the writer and the two catalog readers that find a sequence by its column.

#![allow(clippy::unwrap_used, clippy::expect_used)]

#[path = "parity_harness/mod.rs"]
mod parity;

/// A sequence created after a rolled-back one — the same finding on two rows.
const CONTINUES: &str = "the numbers, not the column: `id` takes one here as it should, but this \
                       session's new sequence continues the rolled-back first session's — `6` \
                       where PostgreSQL starts at `1`. A sequence created after a rolled-back one \
                       that handed out numbers continues them; probed alone, a table's two inserts \
                       rolled back and a new table's first insert is `3`. A finding of its own, \
                       reported with #93 and not its mechanism";

/// What this node answers differently, and why.
const DIVERGENCES: parity::Divergences = parity::Divergences {
    types: &[],
    answers: &[
        (
            "ALTER TABLE later ADD COLUMN id serial",
            "`ADD COLUMN … serial` on a table that already holds rows is refused by name — the \
             rewrite that fills them from the sequence is not built (`crate::exec::ddl`, measured \
             in `captures/pg19_add_column_primary_key.txt`) — and it is not about a key; the next \
             statements read the column it would have added, and go with it",
            "pg19_serial_without_a_key.txt:54",
        ),
        (
            "SELECT 'r', column_name, column_default, is_nullable FROM information_schema.columns \
             WHERE table_name = 'ser' ORDER BY ordinal_position",
            "a sequence outside `public` prints qualified whatever the search path is — \
             `nextval('s2sq2.ser_id_seq'::regclass)`, where PostgreSQL's `regclass` output leaves \
             off a schema the path reaches (`catalog::pg_attribute`, measured with the schema off \
             the path). A rendering gap older than #93, hidden until now behind the `42P01` it \
             fixed",
            "pg19_serial_without_a_key.txt:65",
        ),
        (
            "INSERT INTO ser (v, w) VALUES ('a', 'b') RETURNING v, id, w",
            CONTINUES,
            "pg19_serial_without_a_key.txt:70",
        ),
        (
            "SELECT 'r', nextval('ser_id_seq')",
            CONTINUES,
            "pg19_serial_without_a_key.txt:71",
        ),
    ],
};

#[test]
fn every_serial_without_a_key_answer_is_postgresql_19_s() {
    let checked = parity::replay(
        include_str!("corpus/pg19_serial_without_a_key.txt"),
        &[],
        &DIVERGENCES,
    );
    assert!(
        checked > 40,
        "only {checked} statements ran; the corpus did not load"
    );
}

/// **The number goes in the column the sequence fills**, wherever that column is in the row.
#[test]
fn a_serial_on_a_table_with_no_key_takes_its_number() {
    let mut node = parity::Node::new(&[
        "CREATE TABLE ser (id serial, v text)",
        "CREATE TABLE ser_last (v text, id bigserial, w text)",
    ]);
    assert_eq!(
        node.rows("INSERT INTO ser (v) VALUES ('x'), ('y') RETURNING id, v"),
        [["1", "x"], ["2", "y"]]
    );
    assert_eq!(
        node.rows("INSERT INTO ser_last (v, w) VALUES ('a', 'b') RETURNING v, id, w"),
        [["a", "1", "b"]]
    );
}

/// **An identity column the same, of both kinds.**
#[test]
fn an_identity_on_a_table_with_no_key_takes_its_number() {
    let mut node = parity::Node::new(&[
        "CREATE TABLE ident (id integer GENERATED ALWAYS AS IDENTITY, v text)",
        "CREATE TABLE identd (v text, id bigint GENERATED BY DEFAULT AS IDENTITY)",
    ]);
    assert_eq!(
        node.rows("INSERT INTO ident (v) VALUES ('x') RETURNING id, v"),
        [["1", "x"]]
    );
    assert_eq!(
        node.rows("INSERT INTO identd (v) VALUES ('x') RETURNING v, id"),
        [["x", "1"]]
    );
}

/// **What finds a sequence by its column finds the same one**: `pg_get_serial_sequence` names it
/// for `id` and for no other column, and `DROP COLUMN id` takes it along.
#[test]
fn the_catalog_finds_the_sequence_by_the_column_it_fills() {
    let mut node = parity::Node::new(&["CREATE TABLE ser (v text, id serial, w text)"]);
    assert_eq!(
        node.rows(
            "SELECT pg_get_serial_sequence('ser', 'id'), pg_get_serial_sequence('ser', 'v') IS NULL"
        ),
        [["public.ser_id_seq", "t"]]
    );
    node.run("ALTER TABLE ser DROP COLUMN id").unwrap();
    assert_eq!(
        node.rows("SELECT count(*) FROM pg_class WHERE relname = 'ser_id_seq'"),
        [["0"]]
    );
}

/// **`pg_get_serial_sequence` reads its table the way `::regclass` does**: a bare name along the
/// search path, where it had looked only in `public` and answered `42P01` for a table the same
/// session could insert into — found by this file's capture, whose second session sets the path. A
/// name that is nowhere is still that `42P01`.
#[test]
fn the_serial_sequence_of_a_table_on_the_search_path_is_found() {
    let mut node = parity::Node::new(&["CREATE SCHEMA s", "CREATE TABLE s.t (v text, id serial)"]);
    node.run("SET search_path = s, public").unwrap();
    assert_eq!(
        node.rows("SELECT pg_get_serial_sequence('t', 'id')"),
        [["s.t_id_seq"]]
    );
    assert_eq!(
        node.answer("SELECT pg_get_serial_sequence('nosuch', 'id')")
            .to_string(),
        "!42P01 relation \"nosuch\" does not exist"
    );
}
