//! `pg_attribute` and `pg_attrdef`, computed from the column definitions.
//!
//! The two relations `ActiveRecord`'s `columns()` reads, and between them they are the whole of
//! what a schema dump knows about a column:
//!
//! ```sql
//! SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid),
//!        a.attnotnull, a.atttypid, a.atttypmod, c.collname, col_description(a.attrelid, a.attnum),
//!        attidentity, attgenerated
//!   FROM pg_attribute a
//!   LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
//!   LEFT JOIN pg_type t ON a.atttypid = t.oid
//!   LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
//!  WHERE a.attrelid = '"companies"'::regclass AND a.attnum > 0 AND NOT a.attisdropped
//!  ORDER BY a.attnum
//! ```
//!
//! # The five facts a capture settled and reading would not have
//!
//! Measured on 19beta1 over the fixture in `docs/plans/phase-13-catalog.md` §5:
//!
//! * **An index has attributes too**, one per key column, numbered from 1 in *index* order and
//!   named after the table column: `cb_x_idx` has one row, `x`, `attnum` 1, carrying the column's
//!   own `atttypid` and `atttypmod`. So does a primary key. `count(*)` over `pg_attribute` for an
//!   index is the number of columns in it.
//! * **`attnum <= 0` rows exist on a real server** — `ctid` -1, `xmin` -2, `cmin` -3, `xmax` -4,
//!   `cmax` -5, `tableoid` -6 — so a fifteen-column table has twenty-one rows. This node has none
//!   of those six columns and therefore none of those rows, which is a divergence no
//!   `ActiveRecord` statement can see: every one of them says `attnum > 0`.
//! * **`attidentity` and `attgenerated` are the empty string, not NULL**, for an ordinary column.
//!   `d` is `GENERATED BY DEFAULT AS IDENTITY` and `a` is `GENERATED ALWAYS`.
//! * **An identity column has no `pg_attrdef` row and `atthasdef` is `f`**, where a `bigserial`
//!   has both — `atthasdef` `t` and `nextval('ca_id_seq'::regclass)`. The two look alike in DDL
//!   and are opposite here, and `SequenceDef::identity` is what tells them apart.
//! * **`pg_attrdef` has a row only for a column that has a default**, not one per column: a table
//!   with none has none, and `adnum` is therefore not dense.
//!
//! # `adbin`, and the one thing it is not
//!
//! On a real server `adbin` is a `pg_node_tree` — the parsed expression, which prints as a Lisp-ish
//! dump nobody reads. Here it holds **the printed expression as text**, and `pg_get_expr` is the
//! identity on it. That is a declared divergence in exactly one statement (`SELECT adbin`) and in
//! none that `ActiveRecord` writes, because the only way it ever reads the column is through
//! `pg_get_expr(d.adbin, d.adrelid)`.

use super::NO_LENGTH;
use std::borrow::Cow;

use crate::backend::Txn;
use crate::catalog::pg_relations::{RelKind, RelationRow, Relations};
use crate::catalog::{ColumnDef, Identity, KeyPart, TableDef};
use crate::error::Result;
use crate::value::{ColumnType, Datum, PgType};

/// `attidentity` and `attgenerated` for a column that is neither.
///
/// The empty string, measured — **not** NULL, which is what a reader would assume for "no value"
/// and what `ActiveRecord` would then treat as a missing column rather than an ordinary one.
const NOT_IDENTITY: &str = "";

/// `attgenerated` for a `GENERATED ALWAYS AS (…) STORED` column.
const STORED_GENERATED: &str = "s";

/// `attgenerated` for a **virtual** one — computed on read there, computed and stored here.
///
/// **The only column in which the two kinds differ.** Same values, same recompute on `UPDATE`,
/// same `is_generated = ALWAYS`, same refusal of a non-DEFAULT write; where the bytes live is not
/// visible to SQL, and this letter is.
const VIRTUAL_GENERATED: &str = "v";

/// `attcollation`: none, for every column of every type.
///
/// A real server says `100` for a `text` column and `0` for an `int8` one, and its `pg_type` says
/// the same in `typcollation` — so `a.attcollation <> t.typcollation` is **false for every column**
/// and the `LEFT JOIN pg_collation` in `columns()` yields NULL. Zero here on both sides gives the
/// same NULL for the same reason, and `pg_collation` is empty because this node has no collation
/// feature at all — the argument `pg_range` already makes.
const NO_COLLATION: i64 = 0;

/// `pg_collation` oids, as PostgreSQL numbers them — measured, `C` is 950 and `POSIX` 951, and
/// `default` (the database's own, a locale on the oracle and byte order here) is 100.
const C_COLLATION: i64 = 950;
/// The second name for byte order.
const POSIX_COLLATION: i64 = 951;
/// What a collatable type carries when nothing overrides it.
const DEFAULT_COLLATION: i64 = 100;

/// Every `pg_attribute` row this tenant has.
pub fn rows(txn: &dyn Txn, tenant: u64) -> Result<Vec<Vec<Datum>>> {
    let relations = Relations::read(txn, tenant)?;
    let mut rows = catalog_rows();
    for relation in relations.rows() {
        // **A view answers here too, out of the shape it published when it was created.** It has
        // no `TableDef` to describe, and until the shape was stored there was nothing to say — so
        // `pg_attribute` was empty for a view, which is the one answer a client cannot tell from
        // "no such relation".
        if relation.kind == RelKind::View {
            let Some(columns) = relations.view_columns(relation.table_id) else {
                continue;
            };
            for (attnum, column) in (1..).zip(columns) {
                rows.push(view_attribute(relation, column, attnum));
            }
            continue;
        }
        let Some(table) = relations.table(relation) else {
            continue;
        };
        for (at, (column, position)) in columns_of(relation, table).into_iter().enumerate() {
            rows.push(attribute(relation, &column, table, position, at + 1));
        }
    }
    Ok(rows)
}

/// One `pg_attribute` row for one column of a view.
///
/// **Every flag is a constant, and `attnotnull` is the one worth saying out loud.** Measured on
/// 19beta1: a view over a column declared `NOT NULL` reports `attnotnull` **`f`**. A view's column
/// is the value of an expression, and an expression is nullable whatever it reads — an outer join
/// alone makes a `NOT NULL` column produce NULLs — so the constraint belongs to the table and is
/// not inherited by the relation that selects from it. Nothing here can carry a default, an
/// identity or a generated expression either, and a view has no tombstoned columns because
/// replacing a view rewrites its shape outright.
fn view_attribute(relation: &RelationRow, column: &super::ViewColumn, attnum: i16) -> Vec<Datum> {
    vec![
        Datum::Int8(relation.oid),
        Datum::Text(column.name.clone()),
        Datum::Int8(i64::from(column.ty.oid())),
        Datum::Int2(attnum),
        Datum::Int4(column.typmod),
        Datum::Bool(false),
        Datum::Bool(false),
        // A view's column has no missing value: nothing pads it, the query does.
        Datum::Bool(false),
        Datum::Text(NOT_IDENTITY.to_owned()),
        Datum::Text(NOT_IDENTITY.to_owned()),
        Datum::Bool(false),
        Datum::Int8(NO_COLLATION),
    ]
}

/// **The catalog describes itself here too.** One row per column of every catalog relation.
///
/// A real server's `pg_attribute` has them because its catalog *is* tables, and a client reads
/// them the same way it reads a user table's: `attrelid = 'pg_views'::regclass`. Without these
/// rows that question came back empty, which is a different answer from "four columns" and the
/// one a client cannot tell from "no such relation".
///
/// They are derived from [`super::pg_catalog::CatalogView::columns`] rather than written out, so
/// a column added to a view cannot be missing from the catalog that describes it — the same rule
/// `pg_class`'s own rows follow. Nothing here can carry a default, an identity or a generated
/// expression, so the flags are constants: a catalog relation is computed, and there is nowhere
/// for one to be stored.
fn catalog_rows() -> Vec<Vec<Datum>> {
    let mut rows = Vec::new();
    for view in super::pg_catalog::CatalogView::ALL {
        let oid = i64::try_from(view.table_def().id).unwrap_or(i64::MAX);
        for (attnum, (name, ty, typmod)) in (1..).zip(view.columns()) {
            rows.push(vec![
                Datum::Int8(oid),
                Datum::Text((*name).to_owned()),
                Datum::Int8(i64::from(ty.oid())),
                Datum::Int2(attnum),
                // **The length the view's column list declares**, which is `-1` for all but one
                // family: `information_schema`'s `yes_or_no` columns are a domain over
                // `character varying(3)`, and a real server reports the domain's own typmod for
                // them. The comment here used to say every catalog column is declared at its
                // type's own width, and that was true only while the list had nowhere to say
                // otherwise.
                Datum::Int4(*typmod),
                Datum::Bool(false),
                Datum::Bool(false),
                // No catalog column was ever added by an `ALTER`, so none pads.
                Datum::Bool(false),
                Datum::Text(NOT_IDENTITY.to_owned()),
                Datum::Text(NOT_IDENTITY.to_owned()),
                Datum::Bool(false),
                Datum::Int8(NO_COLLATION),
            ]);
        }
    }
    rows
}

/// Every `pg_attrdef` row this tenant has: one per column that has a default, and no others.
pub fn default_rows(
    txn: &dyn Txn,
    tenant: u64,
    rendering: crate::value::Rendering,
) -> Result<Vec<Vec<Datum>>> {
    let relations = Relations::read(txn, tenant)?;
    let mut rows = Vec::new();
    for relation in relations.of_kind(RelKind::Table) {
        let Some(table) = relations.table(relation) else {
            continue;
        };
        for (attnum, (position, column)) in table.user_columns().enumerate() {
            let Some(expression) = default_expression(column, table, position, rendering) else {
                continue;
            };
            rows.push(vec![
                // `pg_attrdef` has an `oid` of its own on a real server. Here the row is the
                // column, so its identity is the column's: the two are one-to-one and nothing
                // joins on it — `ActiveRecord` joins `a.attrelid = d.adrelid AND a.attnum =
                // d.adnum`, never on this.
                Datum::Int8(relation.oid),
                Datum::Int8(relation.oid),
                Datum::Int2(i16::try_from(attnum + 1).unwrap_or(i16::MAX)),
                Datum::Text(expression),
            ]);
        }
    }
    Ok(rows)
}

/// The columns one relation describes, each with its position in the *table*.
///
/// A table describes its own; an index and a primary key describe the columns they are over, in
/// **key order** rather than table order, which is what makes `cb_yz_idx`'s attributes `y` then
/// `z` whatever order the table declares them in.
///
/// An **expression** key part has no column in the table to describe, and a real server still
/// gives the index relation a row for it: `CREATE INDEX xa_e ON xa (a, (lower(b)))` has
/// `pg_attribute` rows `a bigint` and **`lower text`**. So one is synthesised — named by
/// [`IndexKey::attname`] and typed by the type the expression resolved to when the index was
/// built — rather than skipped, which would leave the relation with fewer attributes than its own
/// `pg_index.indnatts` says it has.
fn columns_of<'a>(
    relation: &RelationRow,
    table: &'a TableDef,
) -> Vec<(Cow<'a, ColumnDef>, Option<usize>)> {
    match relation.kind {
        // **`all_user_columns`, not `user_columns`**: a tombstoned column keeps its `pg_attribute`
        // row on a real server, and the adapter's own query is the one that filters it out
        // (`AND NOT a.attisdropped`). Hiding it here would answer that query correctly and still
        // be wrong — `attnum` would close over the gap, where PostgreSQL leaves it (ADR 0051).
        // **A materialized view describes its own columns exactly as a table does**, because it
        // is one (ADR 0064) — measured: `pg_attribute` over one lists the query's columns with
        // their types, and `attnotnull` is `f` for every one of them, which is what a keyless
        // table with no `NOT NULL` column reports anyway.
        RelKind::Table | RelKind::MaterializedView => table
            .all_user_columns()
            .map(|(at, column)| (Cow::Borrowed(column), Some(at)))
            .collect(),
        RelKind::Index => relation
            .index_at
            .and_then(|at| table.indexes.get(at))
            .map(|index| {
                index
                    .keys
                    .iter()
                    .filter_map(|key| match &key.part {
                        KeyPart::Column(at) => table
                            .columns
                            .get(*at)
                            .map(|column| (Cow::Borrowed(column), Some(*at))),
                        KeyPart::Expression { ty, .. } => Some((
                            Cow::Owned(ColumnDef {
                                collation: None,
                                name: key.attname(table).to_owned(),
                                ty: *ty,
                                typmod: crate::value::NO_TYPMOD,
                                // An index column is nullable, has no default and no missing
                                // value — three facts about the *index*, which stores whatever
                                // the expression evaluated to and never fills a gap.
                                not_null: false,
                                default_expr: None,
                                default: None,
                                missing: None,
                                generated: None,
                                generated_virtual: false,
                                comment: None,
                                dropped: false,
                                user_type: None,
                            }),
                            // No position in the table: there is no column under it, which is
                            // what `attnum = 0` says in `pg_index.indkey` for the same part.
                            None,
                        )),
                    })
                    // **The included columns are attributes of the index too**, after the key's
                    // and in the order written. A real server gives the suite's index four rows
                    // and `a.attnum <= x.indnkeyatts` is what separates the two halves — an index
                    // that described only its key would answer that query with two.
                    .chain(index.include.iter().filter_map(|at| {
                        table
                            .columns
                            .get(*at)
                            .map(|column| (Cow::Borrowed(column), Some(*at)))
                    }))
                    .collect()
            })
            .unwrap_or_default(),
        // An `EXCLUDE`'s index has exactly one attribute, and it is always an expression — a
        // scalar key needs `btree_gist`, which this node does not have, so there is no column
        // form to handle. The type is the one `crate::value::range` answers in.
        RelKind::Exclusion => relation
            .exclude_at
            .and_then(|at| table.excludes.get(at))
            .map(|_| {
                vec![(
                    Cow::Owned(ColumnDef {
                        collation: None,
                        name: "expr".to_owned(),
                        ty: ColumnType::Text,
                        typmod: crate::value::NO_TYPMOD,
                        not_null: false,
                        default_expr: None,
                        default: None,
                        missing: None,
                        generated: None,
                        generated_virtual: false,
                        comment: None,
                        dropped: false,
                        user_type: None,
                    }),
                    None,
                )]
            })
            .unwrap_or_default(),
        RelKind::PrimaryKey => table
            .primary_key
            .iter()
            .filter_map(|at| {
                table
                    .columns
                    .get(*at)
                    .map(|column| (Cow::Borrowed(column), Some(*at)))
            })
            .collect(),
        // **A sequence has no attributes here.** A real server's has three — `last_value`,
        // `log_cnt`, `is_called` — because a sequence there is a one-row relation you can
        // `SELECT` from. Reading a sequence as a relation is `0A000` on this node
        // (`View::require_table`), so describing three columns nothing can read would be claiming
        // a shape rather than reporting one. Declared.
        // **A view's columns are its definition's, and nothing here has them**: `columns_of` is
        // handed a `TableDef` and a view has none, so its shape is what the expansion works out
        // where the view is read rather than something borrowed from a table here.
        RelKind::Sequence | RelKind::View => Vec::new(),
    }
}

/// One `pg_attribute` row.
fn attribute(
    relation: &RelationRow,
    column: &ColumnDef,
    table: &TableDef,
    position: Option<usize>,
    attnum: usize,
) -> Vec<Datum> {
    // Only a **table's** column can carry a default or an identity: an index's attribute is a
    // reference to one, and a real server reports `atthasdef` `f` and `attidentity` `''` for it.
    let own = relation.kind == RelKind::Table;
    let sequence =
        position.and_then(|at| own.then(|| super::pg_relations::sequence_for(table, at)));
    let identity = match sequence.flatten().map(|sequence| sequence.identity) {
        // `bigserial` is a `DEFAULT` and nothing more, so it is not an identity column.
        None | Some(Identity::Default) => NOT_IDENTITY,
        Some(Identity::ByDefault) => "d",
        Some(Identity::Always) => "a",
    };
    let has_default = own
        && !column.dropped
        // **The boot rendering, deliberately** — the default style and UTC: this asks only
        // *whether* there is a default, and
        // whether one exists cannot depend on how it prints.
        && position.is_some_and(|at| {
            default_expression(column, table, at, crate::value::Rendering::default()).is_some()
        })
        && identity == NOT_IDENTITY;
    // **A tombstone answers about itself, not about the column it was.** Measured on 19beta1:
    // the name becomes `........pg.dropped.N........` with the attnum in it, `atttypid` becomes
    // `0`, and `attnotnull` is **reset** to false — while `attlen` is retained, which is why the
    // type is still the column's everywhere the codec reads it and only this view says `0`.
    let name = if column.dropped {
        format!("........pg.dropped.{attnum}........")
    } else {
        column.name.clone()
    };
    // **A user-defined type's own oid**, not the oid of what the value physically is — and the
    // tombstone's `0` wins over both, because a dropped column answers about itself. This is the
    // column every client reads a type through: `format_type(a.atttypid, …)` prints `mood` rather
    // than `smallint`, the `JOIN pg_type t ON a.atttypid = t.oid` that `columns()` writes finds
    // `typtype = 'e'`, and `information_schema.columns` reports `USER-DEFINED` with `udt_name`
    // `mood`. Answering `int2` here would tell a client the storage, which is the one thing about
    // an enum it must not be told (ADR 0050).
    let type_oid = if column.dropped {
        0
    } else {
        column.user_type.map_or_else(
            || i64::from(column.ty.oid()),
            |oid| i64::try_from(oid).unwrap_or(i64::MAX),
        )
    };
    vec![
        Datum::Int8(relation.oid),
        Datum::Text(name),
        Datum::Int8(type_oid),
        Datum::Int2(i16::try_from(attnum).unwrap_or(i16::MAX)),
        Datum::Int4(column.typmod),
        Datum::Bool(own && column.not_null && !column.dropped),
        Datum::Bool(has_default),
        // **`ColumnDef::missing` is the flag.** It is written by `ADD COLUMN` with a *folded*
        // default and is `None` everywhere else — including a `CREATE TABLE` default, an
        // expression default that rewrote the rows, and every column of an index or a sequence —
        // which is exactly PostgreSQL's rule, measured across all five shapes
        // (`tests/att_has_missing.rs`). `own` because a column borrowed onto another relation's
        // row carries none of its owner's defaults.
        Datum::Bool(own && column.missing.is_some()),
        Datum::Text(identity.to_owned()),
        // **One character, and the empty string for a column that is neither** — the same shape
        // `attidentity` has. `s` and `v` are the two kinds of generated column, and this is the
        // only place they differ: everything else about them agrees, including the values.
        Datum::Text(
            match (column.generated.is_some() && own, column.generated_virtual) {
                (true, false) => STORED_GENERATED,
                (true, true) => VIRTUAL_GENERATED,
                (false, _) => NOT_IDENTITY,
            }
            .to_owned(),
        ),
        Datum::Bool(column.dropped),
        Datum::Int8(attcollation(column)),
    ]
}

/// `attcollation`: the collation this column was declared with, or its **type's** default.
///
/// A real server says `950` for `COLLATE "C"`, `951` for `POSIX`, `100` for a collatable column
/// that named none, and `0` for a column of a type that has no collation at all — measured. The
/// gap between the first two and the third is the whole of `ActiveRecord`'s read-back:
/// `a.attcollation <> t.typcollation` names only the columns that asked
/// ([ADR 0076](../../../docs/adr/0076-c-and-posix-are-the-collations-this-node-has.md)).
fn attcollation(column: &ColumnDef) -> i64 {
    match column.collation.as_deref() {
        Some(name) if name.eq_ignore_ascii_case("C") => C_COLLATION,
        Some(name) if name.eq_ignore_ascii_case("POSIX") => POSIX_COLLATION,
        _ => typcollation(column.ty),
    }
}

/// `typcollation`: `100` for the types that have an ordering to override, `0` for the rest.
///
/// The same number a real server reports, and the reason a column that named no collation reads
/// back as none: it equals its type's, so the `<>` in the read-back is false.
pub(crate) fn typcollation(ty: ColumnType) -> i64 {
    match ty {
        // **An array is collatable where its element is** — measured, `_text` and `_varchar` are
        // both `100`, and `CREATE TABLE arr (a text[] COLLATE "C")` is accepted and stores `950`.
        // Which follows: comparing two arrays compares their elements, so the collation the
        // elements would use is the one the array uses.
        ColumnType::Text
        | ColumnType::Varchar
        | ColumnType::Bpchar
        | ColumnType::Citext
        | ColumnType::TextArray
        | ColumnType::VarcharArray
        | ColumnType::BpcharArray
        | ColumnType::CitextArray => DEFAULT_COLLATION,
        // **`name`'s own collation is C**, not the database default: it is the type the catalog
        // is written in, and a catalog has to sort the same way everywhere. Measured — `pg_type`
        // reports 950 for it and `information_schema.columns.collation_name` says `C`, where a
        // `text` column of the same values reports the default.
        ColumnType::Name => C_COLLATION,
        _ => NO_COLLATION,
    }
}

/// Whether a `COLLATE` clause may name this type at all, which is PostgreSQL's own rule and not a
/// second list: a type is collatable exactly when it has a `typcollation` to override. Anything
/// else is `42804 collations are not supported by type <name>` — measured for `integer` and for
/// `uuid`, which is why this asks the type rather than naming the two that were tried.
pub(crate) fn collatable(ty: ColumnType) -> bool {
    typcollation(ty) != NO_COLLATION
}

/// A stored relation name as it goes **inside a string literal**: `schema.name`, each part
/// delimited only if it would not read back as itself.
///
/// `catalog::display_name` joins the two with a dot and stops there, which is right everywhere the
/// name is prose and wrong where it is SQL a client re-parses — and a `nextval` default is the
/// second kind. Measured on 19beta1: `"g1nv_mixed_monkeyID_seq"` quoted, `g1nv_plain_id_seq` and
/// `g1nv_s.t_id_seq` bare.
fn quoted_display_name(stored: &str) -> String {
    let (schema, bare) = super::split_qualified(stored);
    let bare = super::quote_identifier(bare);
    if schema == super::PUBLIC_SCHEMA && !stored.contains(super::SCHEMA_SEPARATOR) {
        return bare;
    }
    format!("{}.{bare}", super::quote_identifier(schema))
}

/// What `pg_get_expr(adbin, adrelid)` prints for one column, or `None` for a column with no
/// default.
///
/// Three sources, and the order matters: an **identity** column has no default expression at all
/// (measured — no `pg_attrdef` row and `atthasdef` `f`), a **`bigserial`** column's default is the
/// `nextval` its sequence makes, and everything else is the stored constant.
pub fn default_expression(
    column: &ColumnDef,
    table: &TableDef,
    at: usize,
    rendering: crate::value::Rendering,
) -> Option<String> {
    // A **volatile** default, which catalog record v5 records as a flag rather than a value
    // (`ColumnDef::default_now`) because a constant cannot express it. It prints unparenthesised,
    // exactly as written — measured, and unlike a computed default such as `DEFAULT 1 + 1`, which
    // a real server prints as `(1 + 1)`.
    // **A generated column's expression lives where a default does.** `pg_get_expr(adbin,
    // adrelid)` returns it — measured — while `information_schema.columns.column_default` for the
    // same column is NULL and `generation_expression` carries the text instead. One `pg_attrdef`
    // row, read by two views that disagree about what it is.
    if let Some(generated) = &column.generated {
        return Some(generated.clone());
    }
    // A default that stayed an **expression**, which the catalog holds as the text `pg_get_expr`
    // prints (`ColumnDef::default_expr`). It comes back verbatim, which is what lets **the
    // spelling the user wrote survive**: a column declared `DEFAULT CURRENT_TIMESTAMP` prints
    // `CURRENT_TIMESTAMP` and one declared `DEFAULT now()` prints `now()`, even though the two are
    // the same function and every row gets the same instant either way. The tag this replaced held
    // one entry for both and could not tell them apart, which was a declared divergence until the
    // text arrived.
    if let Some(expr) = &column.default_expr {
        return Some(expr.clone());
    }
    if let Some(sequence) = super::pg_relations::sequence_for(table, at) {
        return match sequence.identity {
            // `nextval('ca_id_seq'::regclass)`, exactly as a real server prints it — the cast
            // included, which is what `ActiveRecord`'s `pk_and_sequence_for` matches on.
            //
            // **Through `display_name`, because the stored name is not the printed one.** A
            // sequence outside `public` is stored `schema NUL name`, and interpolating that raw
            // put the separator byte into a client's output — `ActiveRecord`'s schema dump printed
            // it inside the `nextval`. Measured, a real server prints a dot:
            // `nextval('g1_ns.t_id_seq'::regclass)`. Invisible in `public`, where the stored name
            // is bare and the two forms are the same string.
            //
            // **And each part is quoted if it needs to be**, inside the literal:
            // `nextval('"mixed_case_monkeys_monkeyID_seq"'::regclass)` for a sequence derived
            // from a mixed-case column, which `primary_keys_test#test_serial_with_quoted_sequence_name`
            // asserts to the character. Measured on 19beta1 beside the two that need no quotes —
            // `nextval('g1nv_plain_id_seq'::regclass)` and `nextval('g1nv_s.t_id_seq'::regclass)`
            // — so the rule is `quote_identifier` per part and not a blanket pair.
            Identity::Default => Some(format!(
                "nextval('{}'::regclass)",
                quoted_display_name(&sequence.name)
            )),
            Identity::ByDefault | Identity::Always => None,
        };
    }
    let value = column.default.as_ref()?;
    if matches!(value, Datum::Null) {
        return None;
    }
    // **A user-defined type's default prints as its label and its own cast**: `'happy'::mood`,
    // not the `3` the row holds — measured on 19beta1 from both `pg_get_expr` and
    // `information_schema.columns.column_default`, and `ActiveRecord`'s `column_defaults` reads
    // exactly this string. The ordinal is storage and a client must never be shown it (ADR 0050).
    if let Some(def) = column
        .user_type
        .and_then(|oid| table.enums.get(&oid))
        .filter(|def| matches!(def.kind, super::TypeKind::Enum { .. }))
    {
        let super::TypeKind::Enum { labels } = &def.kind else {
            return None;
        };
        let Datum::Int2(ordinal) = value else {
            return None;
        };
        let label = super::enum_label(labels, *ordinal)?;
        return Some(format!("'{label}'::{}", def.name));
    }
    Some(super::def_functions::constant_expression(
        value,
        column.ty,
        column.typmod,
        rendering,
    ))
}

/// The columns of `pg_attribute`, in PostgreSQL's own order.
pub const ATTRIBUTE_COLUMNS: &[(&str, ColumnType, i32)] = &[
    ("attrelid", ColumnType::Int8, NO_LENGTH),
    ("attname", ColumnType::Name, NO_LENGTH),
    ("atttypid", ColumnType::Int8, NO_LENGTH),
    ("attnum", ColumnType::Int2, NO_LENGTH),
    ("atttypmod", ColumnType::Int4, NO_LENGTH),
    ("attnotnull", ColumnType::Bool, NO_LENGTH),
    ("atthasdef", ColumnType::Bool, NO_LENGTH),
    // **Whether the column has a *missing value*, which is not whether it has a default.** A
    // default written at `CREATE TABLE` applies to rows written after it and there are no earlier
    // rows to stand in for, so `atthasdef` is `t` and this is `f`; a constant default added by
    // `ALTER TABLE … ADD COLUMN` is stored on the column and padded with, and both are `t`. It is
    // the only way a client can ask whether that `ALTER` rewrote the table.
    ("atthasmissing", ColumnType::Bool, NO_LENGTH),
    ("attidentity", ColumnType::Text, NO_LENGTH),
    ("attgenerated", ColumnType::Text, NO_LENGTH),
    ("attisdropped", ColumnType::Bool, NO_LENGTH),
    ("attcollation", ColumnType::Int8, NO_LENGTH),
];

/// The columns of `pg_attrdef`, in PostgreSQL's own order.
pub const ATTRDEF_COLUMNS: &[(&str, ColumnType, i32)] = &[
    ("oid", ColumnType::Int8, NO_LENGTH),
    ("adrelid", ColumnType::Int8, NO_LENGTH),
    ("adnum", ColumnType::Int2, NO_LENGTH),
    ("adbin", ColumnType::Text, NO_LENGTH),
];
