//! `pg_attribute` and `pg_attrdef`, computed from the column definitions.
//!
//! The two relations `ActiveRecord`'s `columns()` reads, and between them they are the whole of
//! what a schema dump knows about a column:
//!
//! ```sql
//! SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid),
//!        a.attnotnull, a.atttypid, a.atttypmod, c.collname, col_description(a.attrelid, a.attnum),
//!        attidentity, attgenerated
//!   FROM pg_attribute a
//!   LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
//!   LEFT JOIN pg_type t ON a.atttypid = t.oid
//!   LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
//!  WHERE a.attrelid = '"companies"'::regclass AND a.attnum > 0 AND NOT a.attisdropped
//!  ORDER BY a.attnum
//! ```
//!
//! # The five facts a capture settled and reading would not have
//!
//! Measured on 19beta1 over the fixture in `docs/plans/phase-13-catalog.md` §5:
//!
//! * **An index has attributes too**, one per key column, numbered from 1 in *index* order and
//!   named after the table column: `cb_x_idx` has one row, `x`, `attnum` 1, carrying the column's
//!   own `atttypid` and `atttypmod`. So does a primary key. `count(*)` over `pg_attribute` for an
//!   index is the number of columns in it.
//! * **`attnum <= 0` rows exist on a real server** — `ctid` -1, `xmin` -2, `cmin` -3, `xmax` -4,
//!   `cmax` -5, `tableoid` -6 — so a fifteen-column table has twenty-one rows. This node has none
//!   of those six columns and therefore none of those rows, which is a divergence no
//!   `ActiveRecord` statement can see: every one of them says `attnum > 0`.
//! * **`attidentity` and `attgenerated` are the empty string, not NULL**, for an ordinary column.
//!   `d` is `GENERATED BY DEFAULT AS IDENTITY` and `a` is `GENERATED ALWAYS`.
//! * **An identity column has no `pg_attrdef` row and `atthasdef` is `f`**, where a `bigserial`
//!   has both — `atthasdef` `t` and `nextval('ca_id_seq'::regclass)`. The two look alike in DDL
//!   and are opposite here, and `SequenceDef::identity` is what tells them apart.
//! * **`pg_attrdef` has a row only for a column that has a default**, not one per column: a table
//!   with none has none, and `adnum` is therefore not dense.
//!
//! # `adbin`, and the one thing it is not
//!
//! On a real server `adbin` is a `pg_node_tree` — the parsed expression, which prints as a Lisp-ish
//! dump nobody reads. Here it holds **the printed expression as text**, and `pg_get_expr` is the
//! identity on it. That is a declared divergence in exactly one statement (`SELECT adbin`) and in
//! none that `ActiveRecord` writes, because the only way it ever reads the column is through
//! `pg_get_expr(d.adbin, d.adrelid)`.

use crate::backend::Txn;
use crate::catalog::pg_relations::{RelKind, RelationRow, Relations};
use crate::catalog::{ColumnDef, Identity, TableDef};
use crate::error::Result;
use crate::value::{ColumnType, Datum, PgType};

/// `attidentity` and `attgenerated` for a column that is neither.
///
/// The empty string, measured — **not** NULL, which is what a reader would assume for "no value"
/// and what `ActiveRecord` would then treat as a missing column rather than an ordinary one.
const NOT_IDENTITY: &str = "";

/// How a volatile default prints.
///
/// **PostgreSQL keeps the spelling the user wrote**: a column declared `DEFAULT CURRENT_TIMESTAMP`
/// prints `CURRENT_TIMESTAMP` and one declared `DEFAULT now()` prints `now()`, even though the two
/// are the same function and `CURRENT_TIMESTAMP = now()` is `t`. Measured on 19beta1 — and the
/// capture that landed with catalog record v5 says the opposite in its header while showing this in
/// its own rows, so it is worth being explicit.
///
/// `ColumnDef::default_now` is a **bool**, so this node cannot tell the two spellings apart and
/// prints the canonical one for both. Declared in `tests/pg_catalog_attribute.rs`; the *value* a
/// row gets is identical either way, which is why one flag is still the right record.
const CURRENT_TIMESTAMP: &str = "CURRENT_TIMESTAMP";

/// `attcollation`: none, for every column of every type.
///
/// A real server says `100` for a `text` column and `0` for an `int8` one, and its `pg_type` says
/// the same in `typcollation` — so `a.attcollation <> t.typcollation` is **false for every column**
/// and the `LEFT JOIN pg_collation` in `columns()` yields NULL. Zero here on both sides gives the
/// same NULL for the same reason, and `pg_collation` is empty because this node has no collation
/// feature at all — the argument `pg_range` already makes.
const NO_COLLATION: i64 = 0;

/// Every `pg_attribute` row this tenant has.
pub fn rows(txn: &dyn Txn, tenant: u64) -> Result<Vec<Vec<Datum>>> {
    let relations = Relations::read(txn, tenant)?;
    let mut rows = Vec::new();
    for relation in relations.rows() {
        let Some(table) = relations.table(relation) else {
            continue;
        };
        for (at, (column, position)) in columns_of(relation, table).into_iter().enumerate() {
            rows.push(attribute(relation, column, table, position, at + 1));
        }
    }
    Ok(rows)
}

/// Every `pg_attrdef` row this tenant has: one per column that has a default, and no others.
pub fn default_rows(txn: &dyn Txn, tenant: u64) -> Result<Vec<Vec<Datum>>> {
    let relations = Relations::read(txn, tenant)?;
    let mut rows = Vec::new();
    for relation in relations.of_kind(RelKind::Table) {
        let Some(table) = relations.table(relation) else {
            continue;
        };
        for (attnum, (position, column)) in table.user_columns().enumerate() {
            let Some(expression) = default_expression(column, table, position) else {
                continue;
            };
            rows.push(vec![
                // `pg_attrdef` has an `oid` of its own on a real server. Here the row is the
                // column, so its identity is the column's: the two are one-to-one and nothing
                // joins on it — `ActiveRecord` joins `a.attrelid = d.adrelid AND a.attnum =
                // d.adnum`, never on this.
                Datum::Int8(relation.oid),
                Datum::Int8(relation.oid),
                Datum::Int2(i16::try_from(attnum + 1).unwrap_or(i16::MAX)),
                Datum::Text(expression),
            ]);
        }
    }
    Ok(rows)
}

/// The columns one relation describes, each with its position in the *table*.
///
/// A table describes its own; an index and a primary key describe the columns they are over, in
/// **key order** rather than table order, which is what makes `cb_yz_idx`'s attributes `y` then
/// `z` whatever order the table declares them in.
fn columns_of<'a>(
    relation: &RelationRow,
    table: &'a TableDef,
) -> Vec<(&'a ColumnDef, Option<usize>)> {
    match relation.kind {
        RelKind::Table => table
            .user_columns()
            .map(|(at, column)| (column, Some(at)))
            .collect(),
        RelKind::Index => relation
            .index_at
            .and_then(|at| table.indexes.get(at))
            .map(|index| {
                index
                    .columns
                    .iter()
                    .filter_map(|at| table.columns.get(*at).map(|column| (column, Some(*at))))
                    .collect()
            })
            .unwrap_or_default(),
        RelKind::PrimaryKey => table
            .primary_key
            .iter()
            .filter_map(|at| table.columns.get(*at).map(|column| (column, Some(*at))))
            .collect(),
        // **A sequence has no attributes here.** A real server's has three — `last_value`,
        // `log_cnt`, `is_called` — because a sequence there is a one-row relation you can
        // `SELECT` from. Reading a sequence as a relation is `0A000` on this node
        // (`View::require_table`), so describing three columns nothing can read would be claiming
        // a shape rather than reporting one. Declared.
        RelKind::Sequence => Vec::new(),
    }
}

/// One `pg_attribute` row.
fn attribute(
    relation: &RelationRow,
    column: &ColumnDef,
    table: &TableDef,
    position: Option<usize>,
    attnum: usize,
) -> Vec<Datum> {
    // Only a **table's** column can carry a default or an identity: an index's attribute is a
    // reference to one, and a real server reports `atthasdef` `f` and `attidentity` `''` for it.
    let own = relation.kind == RelKind::Table;
    let sequence =
        position.and_then(|at| own.then(|| super::pg_relations::sequence_for(table, at)));
    let identity = match sequence.flatten().map(|sequence| sequence.identity) {
        // `bigserial` is a `DEFAULT` and nothing more, so it is not an identity column.
        None | Some(Identity::Default) => NOT_IDENTITY,
        Some(Identity::ByDefault) => "d",
        Some(Identity::Always) => "a",
    };
    let has_default = own
        && position.is_some_and(|at| default_expression(column, table, at).is_some())
        && identity == NOT_IDENTITY;
    vec![
        Datum::Int8(relation.oid),
        Datum::Text(column.name.clone()),
        Datum::Int8(i64::from(column.ty.oid())),
        Datum::Int2(i16::try_from(attnum).unwrap_or(i16::MAX)),
        Datum::Int4(column.typmod),
        Datum::Bool(own && column.not_null),
        Datum::Bool(has_default),
        Datum::Text(identity.to_owned()),
        // No generated columns: `GENERATED ... AS (expr) STORED` is `0A000` here.
        Datum::Text(NOT_IDENTITY.to_owned()),
        // Nothing can drop a column yet, so no column is dropped.
        Datum::Bool(false),
        Datum::Int8(NO_COLLATION),
    ]
}

/// What `pg_get_expr(adbin, adrelid)` prints for one column, or `None` for a column with no
/// default.
///
/// Three sources, and the order matters: an **identity** column has no default expression at all
/// (measured — no `pg_attrdef` row and `atthasdef` `f`), a **`bigserial`** column's default is the
/// `nextval` its sequence makes, and everything else is the stored constant.
pub fn default_expression(column: &ColumnDef, table: &TableDef, at: usize) -> Option<String> {
    // A **volatile** default, which catalog record v5 records as a flag rather than a value
    // (`ColumnDef::default_now`) because a constant cannot express it. It prints unparenthesised,
    // exactly as written — measured, and unlike a computed default such as `DEFAULT 1 + 1`, which
    // a real server prints as `(1 + 1)`.
    if column.default_now {
        return Some(CURRENT_TIMESTAMP.to_owned());
    }
    if let Some(sequence) = super::pg_relations::sequence_for(table, at) {
        return match sequence.identity {
            // `nextval('ca_id_seq'::regclass)`, exactly as a real server prints it — the cast
            // included, which is what `ActiveRecord`'s `pk_and_sequence_for` matches on.
            Identity::Default => Some(format!("nextval('{}'::regclass)", sequence.name)),
            Identity::ByDefault | Identity::Always => None,
        };
    }
    let value = column.default.as_ref()?;
    if matches!(value, Datum::Null) {
        return None;
    }
    Some(super::def_functions::constant_expression(value, column.ty))
}

/// The columns of `pg_attribute`, in PostgreSQL's own order.
pub const ATTRIBUTE_COLUMNS: &[(&str, ColumnType)] = &[
    ("attrelid", ColumnType::Int8),
    ("attname", ColumnType::Text),
    ("atttypid", ColumnType::Int8),
    ("attnum", ColumnType::Int2),
    ("atttypmod", ColumnType::Int4),
    ("attnotnull", ColumnType::Bool),
    ("atthasdef", ColumnType::Bool),
    ("attidentity", ColumnType::Text),
    ("attgenerated", ColumnType::Text),
    ("attisdropped", ColumnType::Bool),
    ("attcollation", ColumnType::Int8),
];

/// The columns of `pg_attrdef`, in PostgreSQL's own order.
pub const ATTRDEF_COLUMNS: &[(&str, ColumnType)] = &[
    ("oid", ColumnType::Int8),
    ("adrelid", ColumnType::Int8),
    ("adnum", ColumnType::Int2),
    ("adbin", ColumnType::Text),
];
